<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1628850813438' stop='1628851217228'>
    <name>Free racing when logged by Meta Mask</name>
    <title>Free racing when logged by Meta Mask</title>
    <test-cases>
        <test-case start='1628850813438' status='passed' stop='1628850818175'>
            <name>Update metamask info</name>
            <title>Update metamask info</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1628850818175' status='failed' stop='1628850872169'>
            <name>Open ZedRun page and click Connnect Metamask</name>
            <title>Open ZedRun page and click Connnect Metamask</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>TimeoutError: Timeout while waiting for event "close"
                Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.</message>
                <stack-trace>TimeoutError: Timeout while waiting for event "close"
                Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
                    at _rejectOn.promise.then (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/waiter.js:40:51)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1628850872169' status='failed' stop='1628851172172'>
            <name>Check that the ZED app is loading successfully</name>
            <title>Check that the ZED app is loading successfully</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.</message>
                <stack-trace>Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.Error: 
                    at new Spec (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
                    at new Spec (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/setup_jest_globals.js:78:9)
                    at specFactory (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:523:24)
                    at Env.it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:592:24)
                    at Env.it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:134:23)
                    at it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:100:21)
                    at test (/Users/davidle/qa-automationtest/node_modules/jest-retries/src/retry.js:28:5)
                    at Suite.Object.&lt;anonymous>.describe (/Users/davidle/qa-automationtest/tests/gate-nomination/Freegate-Metamask.test.js:78:3)
                    at addSpecsToSuite (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:444:51)
                    at Env.describe (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:414:11)
                    at describe (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:88:18)
                    at Object.&lt;anonymous> (/Users/davidle/qa-automationtest/tests/gate-nomination/Freegate-Metamask.test.js:29:1)
                    at Runtime._execModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:1299:24)
                    at Runtime._loadModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:898:12)
                    at Runtime.requireModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:746:10)
                    at jasmine2 (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/index.js:230:13)
                    at runTestInternal (/Users/davidle/qa-automationtest/node_modules/jest-runner/build/runTest.js:380:22)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1628851172172' status='failed' stop='1628851217228'>
            <name>Select a racehorses and add into the free racing</name>
            <title>Select a racehorses and add into the free racing</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Racing link is not present or clickable</message>
                <stack-trace>Error: Racing link is not present or clickable
                    at HomePage.clickOnRacingLink (/Users/davidle/qa-automationtest/pages/HomePage.js:122:13)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>