<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629459484721' stop='1629459899598'>
    <name>Purchase horse with ETH - Logging with Metamask</name>
    <title>Purchase horse with ETH - Logging with Metamask</title>
    <test-cases>
        <test-case start='1629459484721' status='passed' stop='1629459488970'>
            <name>Update metamask info</name>
            <title>Update metamask info</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1629459488970' status='passed' stop='1629459496901'>
            <name>Open ZedRun page and click Connnect Metamask</name>
            <title>Open ZedRun page and click Connnect Metamask</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1629459496901' status='failed' stop='1629459796916'>
            <name>Go to Marketplace and select first horse</name>
            <title>Go to Marketplace and select first horse</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.</message>
                <stack-trace>Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.Error: 
                    at new Spec (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
                    at new Spec (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/setup_jest_globals.js:78:9)
                    at specFactory (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:523:24)
                    at Env.it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:592:24)
                    at Env.it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:134:23)
                    at it (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:100:21)
                    at test (/Users/davidle/qa-automationtest/node_modules/jest-retries/src/retry.js:28:5)
                    at Suite.Object.&lt;anonymous>.describe (/Users/davidle/qa-automationtest/tests/purchase-horse/metamask-purchase-horse-with-eth.test.js:84:3)
                    at addSpecsToSuite (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:444:51)
                    at Env.describe (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/Env.js:414:11)
                    at describe (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:88:18)
                    at Object.&lt;anonymous> (/Users/davidle/qa-automationtest/tests/purchase-horse/metamask-purchase-horse-with-eth.test.js:48:1)
                    at Runtime._execModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:1299:24)
                    at Runtime._loadModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:898:12)
                    at Runtime.requireModule (/Users/davidle/qa-automationtest/node_modules/jest-runtime/build/index.js:746:10)
                    at jasmine2 (/Users/davidle/qa-automationtest/node_modules/jest-jasmine2/build/index.js:230:13)
                    at runTestInternal (/Users/davidle/qa-automationtest/node_modules/jest-runner/build/runTest.js:380:22)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629459796916' status='failed' stop='1629459899572'>
            <name>Process the checkout with ETH</name>
            <title>Process the checkout with ETH</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: '.ifs .row div.horse-sale-card' could not be found on the page.</message>
                <stack-trace>Error: '.ifs .row div.horse-sale-card' could not be found on the page.
                    at MarketplacePage.waitUntilHorseListLoaded (/Users/davidle/qa-automationtest/pages/MarketplacePage.js:168:29)
                    at test (/Users/davidle/qa-automationtest/tests/purchase-horse/metamask-purchase-horse-with-eth.test.js:92:27)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629459899572' status='failed' stop='1629459899578'>
            <name>Verify that our order is performed</name>
            <title>Verify that our order is performed</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Element is not present or not enabled yet!</message>
                <stack-trace>Error: Element is not present or not enabled yet!
                    at PaymentPage.clickOnBuyWithETH (/Users/davidle/qa-automationtest/pages/PaymentPage.js:184:13)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629459899578' status='failed' stop='1629459899595'>
            <name>Check the detail payment</name>
            <title>Check the detail payment</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: page.bringToFront: Target page, context or browser has been closed</message>
                <stack-trace>page.bringToFront: Target page, context or browser has been closed: 
                    at Connection.sendMessageToServer (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/connection.js:69:15)
                    at Proxy.&lt;anonymous> (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/channelOwner.js:44:61)
                    at _wrapApiCall (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/page.js:385:33)
                    at Page._wrapApiCall (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/channelOwner.js:72:34)
                    at Page.bringToFront (/Users/davidle/qa-automationtest/node_modules/playwright/lib/client/page.js:384:21)
                    at PaymentPage.bringToFront (/Users/davidle/qa-automationtest/pages/PaymentPage.js:23:21)
                    at test (/Users/davidle/qa-automationtest/tests/purchase-horse/metamask-purchase-horse-with-eth.test.js:117:23)
                    at Promise (/Users/davidle/qa-automationtest/node_modules/jest-retries/src/retry.js:3:24)
                    at new Promise (&lt;anonymous>)
                    at runTest (/Users/davidle/qa-automationtest/node_modules/jest-retries/src/retry.js:2:12)
                    at Object.test (/Users/davidle/qa-automationtest/node_modules/jest-retries/src/retry.js:32:23)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629459899595' status='failed' stop='1629459899598'>
            <name>Go back to user stable and check if horse is transferred</name>
            <title>Go back to user stable and check if horse is transferred</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Page instance is not found or not ready</message>
                <stack-trace>Error: Page instance is not found or not ready
                    at ActivityPage.bringToFront (/Users/davidle/qa-automationtest/pages/ActivityPage.js:14:13)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>